src/pages/_document.tsx
src/styles/global-styles.ts
src/styles/globals.css

`desgin/setting-font -> dev`
font 적용했는데 글자가 작아져요..
=> 폰트 사이즈랑 폰트 두께 설정은 size랑 weight로 설정하기로..
reset때문에 폰트가 먹어버려서 글로벌스타일에도 폰트페밀리 적용하니까 되더라구요..
혹시 이상한거 있음 알려주세요!

feat: font 적용

---

package.json
src/pages/preview/index.tsx
src/shared/components/Preview/index.tsx
src/shared/components/Preview/style.ts
src/shared/components/common/Toggle/index.tsx
src/shared/components/common/Toggle/style.ts
src/shared/types/toggleType.ts
yarn.lock

Feat/preview 컴포넌트 구현

---

src/shared/components/TechStackInput/index.tsx

feat/tech-stack-badge -> dev
textContent 타입 추론 X(as 타입 단언 사용)

refactor: textContent 타입 추론 X(as 타입 단언 사용)

---

.eslintrc.json
package.json
yarn.lock

ex) chore/eslint-settings -> dev
- 빌드 에러로 인한 eslint 버전 변경 (9.0.0 -> 8.57)
- eslint rules 변경
-

chore: eslint version & rules 변경

---

src/pages/editor/index.tsx
src/shared/components/Editor/style.ts
src/shared/components/Preview/style.ts

design: preview 컴포넌트와 결합

---

src/pages/index.tsx
src/shared/components/Toast/index.tsx
src/shared/components/Toast/style.ts
src/shared/hooks/useToast/ToastContext.tsx
src/shared/types/toast.ts
src/styles/style.ts

ex) Feat/toast-> dev
1. 토스트 컴포넌트 리뷰받은거 변경했어요~
2. `src/pages => src/styles 로 변경`
PR올리는 김에 스타일 파일위치도 변경했는데 적절한 위치로 옮긴건지 모르겠네요ㅠㅠ 페이지 단위의 스타일 파일은 어디에다가 둬야하는거죵..? styles에 둔다 치면 스타일 파일명을 변경해야할것같네요...

Feat/toast 리뷰 반영 + 스타일 파일 위치 변경

---

.gitignore
src/shared/components/ImageCreateInput/index.tsx

`feat/image-create -> dev`
* width랑 height 입력받기
* 이미지 파일 링크로 변환 API 통신
* 마크다운 생성

이미지 파일 -> 링크로 변환 API

---

package.json
src/shared/components/Preview/CopyButton/index.tsx
src/shared/components/Preview/CopyButton/style.ts
src/shared/components/Preview/index.tsx
src/shared/components/Preview/style.ts
src/shared/components/common/Toggle/style.ts
yarn.lock

케이님이 작업하신 toast를 이용해서 마크다운 복사 구현했습니다.

feat: 복사 기능 구현

---

src/shared/components/Editor/style.ts
src/shared/components/ImageCreateInput/style.ts
src/shared/components/Preview/CopyButton/style.ts
src/shared/components/Preview/Markdown/style.ts
src/shared/components/Preview/style.ts
src/shared/components/TeamTableInput/style.ts
src/shared/components/TechStackInput/style.ts
src/shared/components/common/ProjectInputItem/style.ts

`feat/editor -> dev`
Editor 컴포넌트와 Preview 컴포넌트 width 반응형 적용하였습니다

design: 에디터 페이지 반응형

---

src/shared/components/DefaultSetting/index.tsx
src/shared/components/DefaultSetting/style.ts

ex) feature/default-setting -> dev
defaultSetting component dev브랜치 반영

feat: defaultSetting 컴포넌트 구현

---

src/shared/components/TechStackInput/index.tsx
src/shared/components/TechStackInput/style.ts

feat/match-list-design -> dev
MatchList 반응형 구현
https://github.com/Read-U/readyou-front/assets/162881886/1824d5d8-5c48-45bc-a2a3-e7eca6ed859e

style: matchList 반응현 구현

---

src/shared/components/Editor/index.tsx
src/shared/components/UploadVideoInput/index.tsx
src/shared/components/UploadVideoInput/style.ts

feat/upload-video-design -> dev
동영상 삽입 템플릿 항목 반응형 구현 
https://github.com/Read-U/readyou-front/assets/162881886/8a77b79b-5211-4b67-b8f0-de84c19037f4

style: 동영상 삽입 템플릿 반응형 구현

---

src/shared/components/DefaultSetting/index.tsx
src/shared/components/common/Checkbox/index.tsx

ex) refactor/checkbox -> dev
- checkbox 컴포넌트 속성 defaultChecked -> checked 로 변경
-

feat: checkbox 속성 수정

---

src/shared/components/DefaultSetting/index.tsx
src/shared/components/Editor/index.tsx
src/shared/components/Preview/CopyButton/index.tsx
src/shared/components/TeamTableInput/index.tsx
src/shared/components/TechStackInput/index.tsx
src/shared/components/UploadVideoInput/index.tsx
src/shared/components/common/Button/index.tsx

`feat/editor -> dev`
공통 컴포넌트 헨리 피드백 참고해서 children으로 입력받도록 수정했고, 초기화면의 완료버튼도 추가해놨습니다!
완료/뒤로가기/추가/전체복사 이 4가지 버튼을 두가지로도 분류할 수가 없어서(색상이 같으면 크기가 다르거나 등) 일단 type으로 구분해놨습니다
추후 리팩토링하거나 좋은 방법있으면 알려주세요!

feat: 공통 버튼 컴포넌트 로직 수정

---

src/shared/components/TechStackInput/index.tsx
src/shared/constants/techStackData.tsx

feat/match-list -> dev
연관 데이터 접두사 기준 상위 4개만 보여주게 수정

refactor: 연관 데이터 접두사 기준 상위 4개만 보여주게 수정

---

package.json
src/pages/editor/index.tsx
src/recoil/states.ts
yarn.lock

- recoil persist 설치 
- 새로고침 시 step값과 defaultItem 값이 유지되게 설정
- 전역상태 값 사용시 hydration 에러 방지 코드 작성

feat: recoil persist 적용

---

src/recoil/states.ts
src/shared/components/Editor/index.tsx
src/shared/components/Preview/CopyButton/index.tsx
src/shared/components/Preview/Markdown/index.tsx
src/shared/components/Preview/index.tsx
src/shared/components/ProjectContent/index.tsx
src/shared/components/ProjectTitle/index.tsx
src/shared/constants/editor.ts
src/shared/constants/markdown.ts
src/shared/types/markdown.ts
src/shared/utils/confirmMarkdown.ts

* [] 기능 변경
feat/move-markdown-> dev
https://github.com/Read-U/readyou-front/assets/104294861/f9e770b4-5f37-4253-99e3-071420bac316

feat: 드래그앤드롭 마크다운 동기화 

---

src/shared/components/Preview/CopyButton/index.tsx
src/shared/components/Preview/CopyButton/style.ts
src/shared/components/Preview/Markdown/index.tsx

feat: 복사 방지 구현

---

src/shared/components/Preview/CopyButton/index.tsx
src/shared/components/Preview/Markdown/index.tsx
src/shared/components/ProjectContent/index.tsx
src/shared/components/ProjectDuration/index.tsx

feat: 프로젝트 기간 항목 구현

---

src/recoil/states.ts

fix: recoil-type

---

src/shared/components/ProjectContent/index.tsx
src/shared/components/ProjectTitle/index.tsx

ex) feat/project-title-content-> dev

feat: 새로고침, 뒤로가기시 값 유지 (타이틀, 내용)

---

src/shared/components/TeamTableInput/index.tsx

`feat/table-create -> dev`
팀원테이블 마크다운 프리뷰에 동기화

feat: 팀원테이블 마크다운 프리뷰 동기화

---

src/shared/components/ImageCreateInput/index.tsx

`feat/image-create -> dev`
이미지 마크다운 프리뷰에 동기화

feat: 이미지 마크다운 프리뷰 동기화

---

src/shared/components/ImageCreateInput/index.tsx

feat/markdown-techstack -> dev
기존 파일 확장자 유효성 검사 로직 제거 -> input 태그 기본 속성 accept 사용
accept 사용 전
accept 사용 후

refactor: 이미지 인풋 확장자 제한 로직 제거, accept 속성 사용

---

src/recoil/states.ts
src/shared/components/DefaultSetting/style.ts
src/shared/components/ProjectDuration/index.tsx

refactor: 기간 형식 변경

---

src/shared/components/ProjectDuration/index.tsx

refactor: 기간 예외처리

---

src/shared/components/ImageCreateInput/index.tsx
src/shared/constants/editor.ts
src/shared/types/markdown.ts

`feat/image-create -> dev`
이미지 새로고침 유지
기존 detail에 저장되어 있는 img 마크다운에서 이미지 파일 명을 따올 수가 없어서 imageNameList 새로 만들었습니다!

feat: 이미지 새로고침 유지

---

src/shared/components/ProjectDuration/index.tsx

https://github.com/Read-U/readyou-front/pull/56#discussion_r1555202455 참고
및 console 제거

chore: 불필요한 코드 변경

---

src/shared/components/ProjectContent/index.tsx
src/shared/components/ProjectTitle/index.tsx
src/shared/components/UploadVideoInput/index.tsx

feat/text-input -> dev
프로젝트 제목, 설명 인풋에 띄워쓰기 가능하게 설정
https://github.com/Read-U/readyou-front/assets/162881886/2c4231ff-fb6f-499d-a95e-5c0e040646f2

feat: 프로젝트 제목, 설명 인풋에 띄워쓰기 가능하게 설정

---

src/shared/components/TeamTableInput/index.tsx
src/shared/components/common/ProjectInputItem/index.tsx
src/shared/constants/editor.ts
src/shared/types/markdown.ts

fix: 테이블 초기화 수정

---

src/shared/components/DefaultSetting/index.tsx
src/shared/components/DefaultSetting/style.ts
src/shared/components/common/Checkbox/index.tsx
src/shared/constants/editor.ts

ex) refactor/default-select-> dev
1. 기본 항목 몇개만 체크되게 설정하였습니다.
2. input에서 오류나는거 수정했어요!!
input에 check 속성이 들어가는데 onChange 속성이 안들어가서 계속 오류나는 거였어요!
input과 li 태그 대신에 input이랑 label을 같이 사용하는게 더 좋을것같아요~
https://github.com/Read-U/readyou-front/assets/104294861/98ff94c4-1781-4faa-9f88-772945ad8205

refactor: 기본항목 몇개만 체크되게 설정, input 오류 수정

---

src/shared/components/ImageCreateInput/style.ts
src/shared/components/common/UploadItem/style.ts

fix/global -> dev
업로드 아이템, 이미지 삽입 버튼 패딩 값 조정(텍스트가 중간에 안있고 올라가있음? 수정)

style: padding 값 조정

---

src/shared/components/Preview/Markdown/style.ts

fix/preview-scroll -> dev
스크롤 수정

fix: 프리뷰 스크롤바 수정

---

src/shared/components/Editor/style.ts

fix/editor-scroll -> dev
에디터 스크롤바 수정

fix: 에디터 스크롤바 수정

---

src/pages/editor/index.tsx

feat: editor page header 컴포넌트 구현

---

src/styles/global-styles.ts

fix/global-style -> dev
빌드 환경 폰트 적용 안되는 버그 수정

fix: 빌드 환경 폰트 적용 안되는 버그 수정

---

src/shared/components/ImageCreateInput/index.tsx

feat: 마크다운 추가/삭제 로직 수정

---

src/pages/editor/index.tsx
src/shared/components/DefaultSetting/index.tsx
src/shared/components/DefaultSetting/style.ts
src/shared/components/Editor/style.ts
src/shared/components/Preview/style.ts

ex) feat/preview-scroll -> dev

feat: editor page scroll 스타일 수정

---

src/shared/components/TechStackInput/index.tsx
src/shared/components/UploadVideoInput/index.tsx

fix: 스타일 버그 수정

---

src/shared/components/ImageCreateInput/index.tsx
src/shared/components/TeamTableInput/index.tsx

style: console.log 삭제

---

README.md
package.json
src/pages/editor/index.tsx
src/recoil/states.ts
src/shared/components/DefaultSetting/style.ts
src/shared/components/Editor/index.tsx
src/shared/components/ImageCreateInput/index.tsx
src/shared/components/Preview/Markdown/index.tsx
src/shared/components/Preview/Markdown/style.ts
src/shared/components/Preview/style.ts
src/shared/components/ProjectContent/index.tsx
src/shared/components/ProjectTitle/index.tsx
src/shared/components/RawCode/index.tsx
src/shared/components/RawCode/style.ts
src/shared/components/TeamTableInput/index.tsx
src/shared/components/UploadVideoInput/index.tsx
yarn.lock

ex) feat/rawcode-editor-> dev
로우 코드 수정 방식에 대해 논의해봐야 할 것 같습니다.

feat: 로우코드 에디터 기능 구현

---

src/shared/components/TeamTableInput/index.tsx

`feat/table-fix -> main`
팀원 테이블 생성 시 사용자의 닉네임이 없을 경우 undefined 처리

fix: 팀원테이블 닉네임 없을 경우 undefined 처리

---

src/shared/components/Editor/index.tsx
src/shared/components/Editor/style.ts

feat: 에디터 페이지 DND 관련 토스트 메세지 추가
